# Generated by Django 3.1.7 on 2021-03-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck_box', '0002_deck_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('converted_mana_cost', models.IntegerField(blank=True, null=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=255, null=True)),
                ('toughness', models.CharField(blank=True, max_length=255, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=255, null=True)),
                ('rarity', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(default=0, max_length=255)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'format',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=10)),
                ('release_date', models.DateField(null=True)),
                ('type', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'set',
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='deck',
            table='deck',
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('commander', models.BooleanField(default=False)),
                ('sideboard', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_cards', to='deck_box.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_cards', to='deck_box.deck')),
            ],
            options={
                'db_table': 'deck_card',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='deck_box.set'),
        ),
        migrations.AddField(
            model_name='deck',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='deck_box.format'),
        ),
    ]
